### ISSUE TITLE
<RK⚡️ issue={5} specialEdition="JAMstack / Gatsby" /> - Dec 5, 2019

### ISSUE THREAD

**Issue by wgao19** [react-knowledgeable/events#5]
- 🗓 Date & time: **7:30PM, Dec 5, 2019**
- 🗺 Venue: **Stripe SG, 60 Anson Rd, 05-01 Mapletree Anson, Singapore 079914**, [Google Map](https://www.google.com/maps/place/Stripe+Singapore/@1.274935,103.8431229,17z/data=!3m1!4b1!4m5!3m4!1s0x31da1913a4dcc0ff:0x984d01363a72b9a7!8m2!3d1.274935!4d103.8453116)
- 🔗 RSVP: https://reactknowledgeable.org/meetups/5/

## `<RK />` this month

Our first few events all got JAMstack talks wan, and in case you haven't noticed, [our website](https://reactknowledgeable.org/) is a Gatsby site with many cool features that we're constantly working in progress to build! So we're looking forward to having an RK x JAMstack event end of this year. Also wanna take this chance to help our friends kick off a JAMstack Singapore meetup :] So let's jam on :D

To propose a talk, [create an issue here](https://github.com/react-knowledgeable/talks/issues/new?assignees=&labels=event&template=event.md&title=%3CRK+%2F%3E+%23+-+date) and reference this issue `react-knowledgeable/events#5`

Agenda
---
- **19:00** Door opens and chills
- **19:30** ⚛ React this month
- **19:40** Talks *in no particular order*
  🍯 Deconstructing the JAM react-knowledgeable/talks#30  
  ⚡️ Something about Netlify react-knowledgeable/talks#29
  💸 (Ec)static Commerce react-knowledgeable/talks#31
- **20:15** Networking break
- **20:30** 
  🌏 Navigating i18n in SEA with Gatsby react-knowledgeable/talks#32
  🕹 Yet Another Reason to Buy A Switch (that Has Joy-Cons) react-knowledgeable/talks#33
  👨🏻‍🔧👷🏻‍♂️ Writing a Gatsby plugin react-knowledgeable/talks#34  
- **21:00** We'll have some night snack in a nearby place open jio

---

<details>
<summary>checklist</summary>

- start promoting the event, i.e., tell people about:
  - [x] dec event date / JAMstack theme / proposal open
  - [x] Stripe & venue
- [x] follow up with Gatsby logistics (order placed, whether arrive or not is fingers crossed)
- [x] follow up with JAMstack SG
- [x] confirm talks
- [x] submit event info to engineers.sg 
- pre event
  - [ ] send rsvp name list
  - [ ] pick a snack place (prefer local & relatively quiet)
  - [ ] react updates

</details>

**Comment by wgao19** [comment]
React Updates
—-
- to be updated

**Comment by sayanee** [comment]
Is this the address for Stripe Singapore?

> 89 Neil Rd, 03, Singapore 088849

**Comment by wgao19** [comment]
Hey @sayanee Stripe is moving to a new office and prefers to not publish the new address yet. Would like to ask @thorsten-stripe to help update the venue info.

**Comment by thorsten-stripe** [comment]
Hey all :) we've finished our move and have updated our Google Maps listing: https://goo.gl/maps/TFVjcDKhoxZHHSBT9 

Please do post the new address: 60 Anson Road, Mapletree Anson #05-01 Singapore 079914
