### ISSUE TITLE
<RK⚡️ issue={6} /> - Jan 9, 2020

### ISSUE THREAD

**Issue by wgao19** [react-knowledgeable/events#6]
🗓 Date: Thursday, Jan 9, 2020
🗺 Venue: TBD (we need venue!)
🦄 Host: @email2vimalraj
📨 Link to RSVP: https://reactknowledgeable.org/meetups/6/

## `<RK />` this month

2020 is coming and in the new year we also want to keep improving our minds as a React developer. Our Jan event will happen Jan 9. It's a Thursday. And we'll resume our learning / sharing journey around React.

At the same time, RK is also learning wan. Next month, we'll cap at 5 talks and will pair our supper with some light refreshments so we won't sound like hungry monkeys.

Speaking at this event
---
To propose a talk, [create an issue here](https://github.com/react-knowledgeable/talks/issues/new?assignees=&labels=event&template=event.md&title=%3CRK+%2F%3E+%23+-+date) and reference `react-knowledgeable/events#6`. 

Agenda
---
- **19:00** Door opens and chills
- **19:30** ⚛ React this month
- **19:40** First 3 talks
- **20:15** Networking break
- **20:30** Last 2 talks && talks from the ground
- **21:00** Go home

---

<details>
  <summary>checklist</summary>

- issue creation
  - [x] github issue
  - [ ] website
  - [ ] calendar event
  - [ ] submit event info to [engineers.sg's spreadsheet](https://docs.google.com/spreadsheets/d/1N8kiq4PFp2Z8POsqhX6GIBBZGxNB3itfC_3l1_TdzCY/edit#gid=0)
- tweets
  - [ ] event date / cfp / link to page
  - [ ] venue sponsor
  - [ ] engineers.sg
  - [ ] theme if applicable
  - [ ] talk proposals
- pre event
  - [ ] send rsvp name list
  - [ ] pick a snack place (prefer local & relatively quiet)
  - [ ] react updates
  
</details>

**Comment by rctay** [comment]
Hi there, what does the agenda of talks look like right now?

**Comment by wgao19** [comment]
hey @rctay we have one confirmed talk (quicksort) referenced here above

in the rare situation our dec event runs over, we may have the joycon (something about the gamepad api) in jan too. but we dont expect this to happen

**Comment by wgao19** [comment]
hey @email2vimalraj as per discussed in #37 the talk is rescheduled to feb
